In [1]:
import numpy as np
import torch

In [6]:
# Using numpy
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

print(np.round(A@B, 2)), print(' ')
print(np.round(C.T@A, 2)), print(' ')

[[-0.55 -1.72 -0.22 -0.54 -1.47]
 [ 0.69  2.21 -0.49 -0.31 -3.53]
 [ 1.6   0.3  -0.45 -0.48 -1.83]]
 
[[ 0.73 -0.31  0.37 -0.78]
 [-0.51  1.49 -1.43  0.99]
 [ 1.85 -0.52  0.66 -0.49]
 [-0.09  0.81 -0.78  1.1 ]
 [ 1.84  1.84 -1.59  3.16]
 [-0.39  0.78 -0.74  0.05]
 [ 1.56  0.03  0.1   0.52]]
 


(None, None)

In [10]:
# Using pytorch
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C = torch.randn(3, 7)
D1 = np.random.randn(4, 5)
D2 = torch.tensor(D1, dtype=torch.float)

print(np.round(A@B, 2)), print(' ')
print(np.round(C.T@A, 2)), print(' ')
print(np.round(A@D1, 2)), print(' ')
print(np.round(A@D2, 2)), print(' ')

tensor([[ 0.9500, -0.3900,  0.3500,  0.6100,  0.9100],
        [ 0.3300,  0.3300,  0.2300, -0.7400, -4.1500],
        [-0.5700,  0.4600, -0.3200, -0.5700, -0.2600]])
 
tensor([[ 1.1100, -0.5700, -0.4700,  0.2200],
        [ 0.8600, -0.1900, -0.7700, -0.3100],
        [-1.0100,  2.1700, -1.6700, -3.0800],
        [ 0.0500, -1.6200,  1.3900,  2.4600],
        [ 0.5400, -1.3600,  0.9200,  1.8700],
        [ 0.1200, -0.0500, -0.1100, -0.0200],
        [-2.7700,  2.4500,  0.0800, -2.2200]])
 
tensor([[ 0.6000,  0.4000,  0.9900, -0.7000,  0.1300],
        [-0.5700,  0.9200, -2.5000, -0.6600, -2.2900],
        [-0.5600,  0.2500, -0.6700,  0.6000, -0.0300]], dtype=torch.float64)
 
tensor([[ 0.6000,  0.4000,  0.9900, -0.7000,  0.1300],
        [-0.5700,  0.9200, -2.5000, -0.6600, -2.2900],
        [-0.5600,  0.2500, -0.6700,  0.6000, -0.0300]])
 


(None, None)