In [1]:
import numpy as np
import torch

In [2]:
v = np.array([1, 40, 5, 2, -3])

minval = np.min(v)
maxval = np.max(v)
print("Min, max: %g, %g"%(minval, maxval))

minidx = np.argmin(v)
maxidx = np.argmax(v)
print("Min, max indices: %d, %d"%(minidx, maxidx))

Min, max: -3, 40
Min, max indices: 4, 1


In [9]:
M = np.array([[0, 1, 10], [20, 8, 5]])
print(M), print(" ")

minval1 = np.min(M)
minval2 = np.min(M, axis=0) # min of each column (across rows)
minval3 = np.min(M, axis=1) # min of each row (across columns)

print(minval1)
print(minval2)
print(minval3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


In [10]:
minidx1 = np.argmin(M)
minidx2 = np.argmin(M, axis=0) # minimum of each column (across rows)
minidx3 = np.argmin(M, axis=1) # minimum of each row (across columns)

print(M), print(' ')
print(minidx1)
print(minidx2)
print(minidx3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]


# Using pytorch

In [11]:
v = torch.tensor([1, 40, 5, 2, -3])

minval = torch.min(v)
maxval = torch.max(v)
print("Min, max: %g, %g"%(minval, maxval))

minidx = torch.argmin(v)
maxidx = torch.argmax(v)
print("Min, max indices: %d, %d"%(minidx, maxidx))

Min, max: -3, 40
Min, max indices: 4, 1


In [13]:
M = torch.tensor([[0, 1, 10], [20, 8, 5]])
print(M), print(" ")

min1 = torch.min(M)
min2 = torch.min(M, dim=0) # min of each column (across rows)
min3 = torch.min(M, dim=1) # min of each row (across columns)

print(min1)
print(min2)
print(min3)
print(min2.values)
print(min2.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))
tensor([0, 1, 5])
tensor([0, 0, 1])
