In [1]:
import numpy as np
import torch

In [2]:
# Using numpy
nv = np.array([[1, 2, 3, 4]])
print(nv)

print(nv.T)

nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [3]:
# Using pytorch
pt = torch.tensor([[1, 2, 3, 4]])
print(pt)

print(pt.T)

ptT = pt.T
print(ptT.T)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3, 4]])


In [4]:
# Examine dt
print(f'Variable nv is of type {type(nv)}')
print(f'Variable pt is of type {type(pt)}')

Variable nv is of type <class 'numpy.ndarray'>
Variable pt is of type <class 'torch.Tensor'>
